<?php

namespace ApiCrumbs\Core\Commands;

class MakeCommand
{
    public function handle(array $args): void
    {
        $name = $args[2] ?? null;

        if (!$name) {
            echo "\e[31m❌ Error: Please provide a provider name (e.g. php foundry make Shopify)\e[0m\n";
            exit(1);
        }

        $className = ucfirst($name) . "Provider";
        $directory = getcwd() . "/src/Providers";
        
        // Create directory if missing
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $directory = getcwd() . "/src/Providers/Custom";
        
        // Create directory if missing
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $filePath = "{$directory}/{$className}.php";

        if (file_exists($filePath)) {
            echo "\e[33m⚠️  Warning: {$className} already exists at {$filePath}\e[0m\n";
            exit(1);
        }

        $stub = $this->getStub(ucfirst($name), $className);
        
        if (file_put_contents($filePath, $stub)) {
            echo "\e[32m✨ Success! Created Crumb Provider: {$className}\e[0m\n";
            echo "\e[34m📍 Location: {$filePath}\e[0m\n";
            echo "\nRegister it with: \e[1m\$crumbs->registerProvider(new \\ApiCrumbs\\Providers\\Custom\\{$className}());\e[0m\n";
        }
    }

    private function getStub($name, $className): string
    {
        return <<<PHP
<?php

namespace ApiCrumbs\Providers\Custom;

use ApiCrumbs\Core\Contracts\ProviderInterface;

/**
 * Custom Provider for {$name}
 * Generated by ApiCrumbs Foundry (Native)
 */
class {$className} implements ProviderInterface
{
    public function getName(): string 
    { 
        return '{$name}_context'; 
    }

    public function fetchData(string \$id): array
    {
        // Add your API logic here
        return [
            'id' => \$id,
            'status' => 'active',
            'note' => 'Generated by ApiCrumbs Foundry'
        ];
    }
}
PHP;
    }
}