<?php

namespace ApiCrumbs\Core\Commands;

class MakeCommand
{
    public function handle(array $args): void
    {
        $name = $args[2] ?? null;

        if (!$name) {
            echo "\e[31m❌ Error: Please provide a provider name (e.g. php foundry make Shopify)\e[0m\n";
            exit(1);
        }

        $className = ucfirst($name) . "Provider";
        $directory = getcwd() . "/src/Providers";
        
        // Create directory if missing
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $directory = getcwd() . "/src/Providers/Custom";
        
        // Create directory if missing
        if (!is_dir($directory)) {
            mkdir($directory, 0755, true);
        }

        $filePath = "{$directory}/{$className}.php";

        if (file_exists($filePath)) {
            echo "\e[33m⚠️  Warning: {$className} already exists at {$filePath}\e[0m\n";
            exit(1);
        }

        // --- NEW INTERACTIVE PROMPT ---
        echo "\e[36m🔗 Dependency Wizard:\e[0m Enter provider names this depends on (comma separated), or press Enter for none:\n> ";
        $input = trim(fgets(STDIN));
        
        $deps = [];
        if (!empty($input)) {
            $deps = array_map('trim', explode(',', $input));
        }

        $formattedDeps = "['" . implode("', '", $deps) . "']";
        if (empty($deps)) $formattedDeps = "[]";

        $stub = $this->getStub(ucfirst($name), $className, $formattedDeps);
        
        if (file_put_contents($filePath, $stub)) {
            echo "\e[32m✨ Success! Created Crumb Provider: {$className} with dependencies: {$formattedDeps}\e[0m\n";
            echo "\e[34m📍 Location: {$filePath}\e[0m\n";
            echo "\nRegister it with: \e[1m\$crumbs->registerProvider(new \\ApiCrumbs\\Providers\\Custom\\{$className}());\e[0m\n";
        }
    }

    private function getStub($name, $className, $deps): string
    {
        $getName = strtolower($name);
        
        return <<<PHP
<?php

namespace ApiCrumbs\Providers\Custom;

use ApiCrumbs\Core\Contracts\ProviderInterface;

/**
 * Custom Provider for {$name}
 * Generated by ApiCrumbs Foundry (Native)
 */
class {$className} implements ProviderInterface
{
    public function getName(): string 
    { 
        return '{$getName}_context'; 
    }

    public function getDependencies(): array 
    { 
        return {$deps}; 
    }

    public function fetchData(string \$id, array \$context = []): array
    {
        // Access dependencies via \$context['provider_name']
        return [
            'source' => '{$name}',
            'data' => []
        ];
    }
}
PHP;
    }
}